version: '3.7'
services:
  client:
    build: ./client # Location of the Dockerfile for the client
    restart: always
    volumes:
      - ./.caddy:/root/.caddy  # to save certificates on disk
    environment: 
      CADDY_HOST: "localhost" # The domain/host to serve to
      CADDY_TLS: "off" # Set to email address to enable TLS
      ACME_AGREE: "true" # Set to true to agree to the Let's Encrypt Subscriber Agreement (https://letsencrypt.org/documents/2017.11.15-LE-SA-v1.2.pdf)
    ports:
      - "2015:2015" 
      - "80:80" # http
      - "443:443" # https
    depends_on: 
      - server
  server:
    build: ./server # Location of the Dockerfile for the client
    restart: always
    environment: 
      MONGO_ADDR: mongo # hostname of the mongo container
    depends_on: 
      - mongo
  mongo:
      image: mongo:3.4.23
      restart: always
      volumes:
          - mongo_data:/data/db

volumes: 
  mongo_data: