version: '3.7'
services:
  caddy:
    image: "wemakeservices/caddy-docker:latest"
    volumes:
      - ./.caddy:/root/.caddy  # to save certificates on disk
      - ./Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    depends_on:
      - client

  client:
    build: ./client
    ports:
      - "8000:80"
