version: '3.7'
services:

  client:
    build: ./client
    restart: always
    volumes:
      - ./.caddy:/root/.caddy  # to save certificates on disk
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    depends_on: 
      - server
  server:
    build: ./server
    restart: always
    environment: 
      MONGO_ADDR: mongo
    depends_on: 
      - mongo
  mongo:
      image: mongo:3.4.23
      restart: always