/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package umm3601;

import java.util.Arrays;

import com.mongodb.MongoClientSettings;
import com.mongodb.ServerAddress;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;

import org.bson.BsonDocument;
import org.bson.BsonString;

import io.javalin.Javalin;

public class Server {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        String mongoAddr = System.getenv().get("MONGO_ADDR");
        
        MongoClient mongoClient = MongoClients.create(
            MongoClientSettings.builder()
                    .applyToClusterSettings(builder ->
                            builder.hosts(Arrays.asList(new ServerAddress(mongoAddr != null ? mongoAddr : "localhost"))))
                    .build());

        MongoDatabase database = mongoClient.getDatabase("admin");

        Javalin app = Javalin.create().start(4567);
        app.get("/api", ctx -> ctx.result("Hello World"));
        app.get("/api/mongo", ctx -> ctx.result(database.runCommand(new BsonDocument("buildinfo", new BsonString(""))).toJson()));
    
    }
}
